// Generated by scripts/generate-pi-closure.mts from pnpm-lock.yaml — do not edit by hand.
// Regenerate after a @earendil-works/pi-coding-agent bump; closure-gen.test.ts guards against drift.
import type { NpmClosure } from './closure';

const packages: NpmClosure['packages'] = [
  {
    name: '@anthropic-ai/sdk',
    version: '0.91.1',
    integrity:
      'sha512-LAmu761tSN9r66ixvmciswUj/ZC+1Q4iAfpedTfSVLeswRwnY3n2Nb6Tsk+cLPP28aLOPWeMgIuTuCcMC6W/iw==',
    path: 'node_modules/@anthropic-ai/sdk',
  },
  {
    name: '@aws-crypto/crc32',
    version: '5.2.0',
    integrity:
      'sha512-nLbCWqQNgUiwwtFsen1AdzAtvuLRsQS8rYgMuxCrdKf9kOssamGLuPwyTY9wyYblNr9+1XM8v6zoDTPPSIeANg==',
    path: 'node_modules/@aws-crypto/crc32',
  },
  {
    name: '@aws-crypto/sha256-browser',
    version: '5.2.0',
    integrity:
      'sha512-AXfN/lGotSQwu6HNcEsIASo7kWXZ5HYWvfOmSNKDsEqC4OashTp8alTmaz+F7TC2L083SFv5RdB+qU3Vs1kZqw==',
    path: 'node_modules/@aws-crypto/sha256-browser',
  },
  {
    name: '@aws-crypto/sha256-js',
    version: '5.2.0',
    integrity:
      'sha512-FFQQyu7edu4ufvIZ+OadFpHHOt+eSTBaYaki44c+akjg7qZg9oOQeLlk77F6tSYqjDAFClrHJk9tMf0HdVyOvA==',
    path: 'node_modules/@aws-crypto/sha256-js',
  },
  {
    name: '@aws-crypto/supports-web-crypto',
    version: '5.2.0',
    integrity:
      'sha512-iAvUotm021kM33eCdNfwIN//F77/IADDSs58i+MDaOqFrVjZo9bAal0NK7HurRuWLLpF1iLX7gbWrjHjeo+YFg==',
    path: 'node_modules/@aws-crypto/supports-web-crypto',
  },
  {
    name: '@aws-crypto/util',
    version: '5.2.0',
    integrity:
      'sha512-4RkU9EsI6ZpBve5fseQlGNUWKMa1RLPQ1dnjnQoe07ldfIzcsGb5hC5W0Dm7u423KWzawlrpbjXBrXCEv9zazQ==',
    path: 'node_modules/@aws-crypto/util',
  },
  {
    name: '@aws-sdk/client-bedrock-runtime',
    version: '3.1048.0',
    integrity:
      'sha512-u+NT61JZEkRFtpL0CAw1N1dwxnaLgwVXQl/zjJxTGgLyS/jTIdg2SdoEoCTHxgDyCnqa1HEi9QOoE9/pYRNpOQ==',
    path: 'node_modules/@aws-sdk/client-bedrock-runtime',
  },
  {
    name: '@aws-sdk/token-providers',
    version: '3.1048.0',
    integrity:
      'sha512-k0y/GcuesuSfWyUM0WamrGyeZmltRYaPbHO82UDA6mZ/doB+FOHKutikPAtSXMn/hDz970cF+iRuuiYO9VEbAA==',
    path: 'node_modules/@aws-sdk/client-bedrock-runtime/node_modules/@aws-sdk/token-providers',
  },
  {
    name: '@aws-sdk/core',
    version: '3.974.21',
    integrity:
      'sha512-P5JAHvn4dTi96UsAGS67LVOqqpUNNRhnfFXqzCYtdBIGZtqBue4CXvRr9YenOO7PALj/Pn8uuyw53FBCiCYw8w==',
    path: 'node_modules/@aws-sdk/core',
  },
  {
    name: '@aws-sdk/credential-provider-env',
    version: '3.972.47',
    integrity:
      'sha512-3YoPwJczcc+MtX2xxXaYaOOWO6xKUJr1ZIIDIFuninr51BYONVVcF/CP8K2xfVRC/PztJjqKWxNGFH7BWQAw1Q==',
    path: 'node_modules/@aws-sdk/credential-provider-env',
  },
  {
    name: '@aws-sdk/credential-provider-http',
    version: '3.972.49',
    integrity:
      'sha512-2UtGUPy+x3lqyceHrtC1uEuVxBZbDalPF6KAFqBwYgm4edWdBrZKNnCqzDs7KynWUvEC6mrR+ojRk+ZgQz9C2w==',
    path: 'node_modules/@aws-sdk/credential-provider-http',
  },
  {
    name: '@aws-sdk/credential-provider-ini',
    version: '3.972.54',
    integrity:
      'sha512-Hx4gO4YRjFwitf3MVl3cDwYe1aryJthC4txVl9b+JAURovA50M2ywf9r8j1E/Q6SCTPT4qQpjOAbKYIC9CG+Vw==',
    path: 'node_modules/@aws-sdk/credential-provider-ini',
  },
  {
    name: '@aws-sdk/credential-provider-login',
    version: '3.972.53',
    integrity:
      'sha512-+71sluhkgPqdhbbD3UDwUpj24GCkng9HQx6z7qoBFb8dwkF4ktpOcVKDeHpgg8PvBgLYwAnUYLTEGRC/PniCiQ==',
    path: 'node_modules/@aws-sdk/credential-provider-login',
  },
  {
    name: '@aws-sdk/credential-provider-node',
    version: '3.972.56',
    integrity:
      'sha512-iI+4o0dvQQ4NHel4FMDiFy5q2gaU/ryLK3niOsoPccAt9WLFRkV4XTYPWRr9XvmBUqEzXG73S4p/8gm0Lu/W3A==',
    path: 'node_modules/@aws-sdk/credential-provider-node',
  },
  {
    name: '@aws-sdk/credential-provider-process',
    version: '3.972.47',
    integrity:
      'sha512-tAizPm9IFo/PHn06c+LQJlzfY2AGOlyF0CUljFejrU6LcZBjnk8pmbZK3/xoIDdnIzjEdbClfvY3mXfr818ZEg==',
    path: 'node_modules/@aws-sdk/credential-provider-process',
  },
  {
    name: '@aws-sdk/credential-provider-sso',
    version: '3.972.53',
    integrity:
      'sha512-pUXE3fu4tfEDV8BksIgf4dXvuIH10FhwHMl/wu8rBD5T1sMpryQWFVitH3kdPS90wlgrGYJQ/meQTSPacyZfeg==',
    path: 'node_modules/@aws-sdk/credential-provider-sso',
  },
  {
    name: '@aws-sdk/credential-provider-web-identity',
    version: '3.972.53',
    integrity:
      'sha512-JmMGlhVvSj8uSG9CpeDkJAXT35H89tc6v84iMgEIE75q4yp1MKVVKvopv6Gg28HJIR7hMNkojRF8H2m5W44wyg==',
    path: 'node_modules/@aws-sdk/credential-provider-web-identity',
  },
  {
    name: '@aws-sdk/eventstream-handler-node',
    version: '3.972.22',
    integrity:
      'sha512-tqPJv0dz4+O0hWGm1a6YekcMZyPhDFs/zH73Von7icaVT5n0Jqvm86typ3jRrG+qoUdPhALOnboRLTmnWQTlYQ==',
    path: 'node_modules/@aws-sdk/eventstream-handler-node',
  },
  {
    name: '@aws-sdk/middleware-eventstream',
    version: '3.972.18',
    integrity:
      'sha512-OHpk8YoZi3yexPq8aFt1vN1IxA2zLKvsIR5GpWYylX/ve6kQmY7wxHNSFy/D3t2apMZ16rs76Co4dJWcDyIk3A==',
    path: 'node_modules/@aws-sdk/middleware-eventstream',
  },
  {
    name: '@aws-sdk/middleware-websocket',
    version: '3.972.29',
    integrity:
      'sha512-Agv95NCgYyvuYUXt2PcFcOMrKCkhBFPhoH+nVMQh85RcXSCQrhAa4475plBOeomCihP26vKHT5KinVQT3iD14w==',
    path: 'node_modules/@aws-sdk/middleware-websocket',
  },
  {
    name: '@aws-sdk/nested-clients',
    version: '3.997.21',
    integrity:
      'sha512-eC7Vl7Qom/BGhZjG9GEqPwdQ/fk45hg1t5LP4EUxG5d1fdshLbaxCiwh/tszUzDX/4mW40mu2QsbeJJRPBbqUw==',
    path: 'node_modules/@aws-sdk/nested-clients',
  },
  {
    name: '@aws-sdk/signature-v4-multi-region',
    version: '3.996.35',
    integrity:
      'sha512-6L/VWs+Wch2stHemCGTmUNqKLMzURxQDK5boNG3Jn3kAOp71meDUuS5sbObpEvFxHDq0uWeSLFDNSYsjNt+Dlg==',
    path: 'node_modules/@aws-sdk/signature-v4-multi-region',
  },
  {
    name: '@aws-sdk/token-providers',
    version: '3.1069.0',
    integrity:
      'sha512-ks4X+kngC3PA5howV7Qu1TgG4bfC4jPykKdvw3nmBSXR9yZxRJouBholFSNQ5kY3L+Fgwyw+LCjzQmNi+KR91g==',
    path: 'node_modules/@aws-sdk/token-providers',
  },
  {
    name: '@aws-sdk/types',
    version: '3.973.13',
    integrity:
      'sha512-pEHZqRkAlHfnfAU9tK+WpKv/gBNjGJrHMgA3A0iYRGyswBS2t0pfez+lWlwktb3Bqa0ovh7w/QJTFwp3fDxLNg==',
    path: 'node_modules/@aws-sdk/types',
  },
  {
    name: '@aws-sdk/util-locate-window',
    version: '3.965.8',
    integrity:
      'sha512-uUbMs1cBZPafD0ohUj6EwNf0fPZ534NvBxHox4hjX+0Rxq5paSYUem7+hi833pYrzrcnBATKIYpR02MDXT5M9g==',
    path: 'node_modules/@aws-sdk/util-locate-window',
  },
  {
    name: '@aws-sdk/xml-builder',
    version: '3.972.30',
    integrity:
      'sha512-StElZPEoBquWwNqw1AcfpzEyZqJvFxouG+mpDNYlcH6ZOrqd2CuIryv+8LV8gNHZUOyKyJF3Dq9vxaXEmDR9TQ==',
    path: 'node_modules/@aws-sdk/xml-builder',
  },
  {
    name: '@aws/lambda-invoke-store',
    version: '0.2.4',
    integrity:
      'sha512-iY8yvjE0y651BixKNPgmv1WrQc+GZ142sb0z4gYnChDDY2YqI4P/jsSopBWrKfAt7LOJAkOXt7rC/hms+WclQQ==',
    path: 'node_modules/@aws/lambda-invoke-store',
  },
  {
    name: '@babel/runtime',
    version: '7.29.7',
    integrity:
      'sha512-Nq8OhGWiZIZGV6hLHoyAKLLcJihP/xFeBMGJoUrxTX2psI8dCifzLhZISFb+VWS3wFMRDmCGw5R+dOySCqPLhw==',
    path: 'node_modules/@babel/runtime',
  },
  {
    name: '@earendil-works/pi-agent-core',
    version: '0.80.6',
    integrity:
      'sha512-Lvn89ko42h5ETUb6Z0Ku6ldskEqXaTdQBYvSa0+7bdG9V6rUEpXptv5e0OVZ1HDcvi8s6/2lGCQWsxKX+DFHNw==',
    path: 'node_modules/@earendil-works/pi-agent-core',
  },
  {
    name: '@earendil-works/pi-ai',
    version: '0.80.6',
    integrity:
      'sha512-7xfLk8sANBp+bpPEbjoOZTbPxsa+++b1JXAoSJsNa3vbs9AHHEclmvg54XLQcxH+fuwaeti/g2jeIfJ+mVYLpA==',
    path: 'node_modules/@earendil-works/pi-ai',
  },
  {
    name: '@smithy/node-http-handler',
    version: '4.7.3',
    integrity:
      'sha512-/jPhevcTFPMVl6KNjbaI47iOg1zxC7IsnX4PQDGVZKMFceOXtB8IEYaB7a9VvkP/3oC60WzTeKocvSI7vLT0vA==',
    path: 'node_modules/@earendil-works/pi-ai/node_modules/@smithy/node-http-handler',
  },
  {
    name: '@earendil-works/pi-coding-agent',
    version: '0.80.6',
    integrity:
      'sha512-vcfD6tOk402isLl3Cm/qbn2O10TvgroMp1+/fEGM24ZdvETFCdOYv5VZ7m59EI5fPsjfSJh+CpQ5bhBrhfOg7g==',
    path: 'node_modules/@earendil-works/pi-coding-agent',
  },
  {
    name: '@earendil-works/pi-tui',
    version: '0.80.6',
    integrity:
      'sha512-bSuzS4EVSqEPj/Qr/p9eqCESfKsGuDNbl77EGci8Iaqqt/C/XCBZL1MjXaxSWW1NsT5afjp/Cb0NTPzOLv/aPA==',
    path: 'node_modules/@earendil-works/pi-tui',
  },
  {
    name: '@google/genai',
    version: '1.52.0',
    integrity:
      'sha512-gwSvbpiN/17O9TbsqSsE/OzZcpv5Fo4RQjdngGgogtuB9RsyJ8ZHhX5KjHj1bp5N9snN2eK8LDGXSaWW2hof8Q==',
    path: 'node_modules/@google/genai',
  },
  {
    name: '@hono/node-server',
    version: '1.19.14',
    integrity:
      'sha512-GwtvgtXxnWsucXvbQXkRgqksiH2Qed37H9xHZocE5sA3N8O8O8/8FA3uclQXxXVzc9XBZuEOMK7+r02FmSpHtw==',
    path: 'node_modules/@hono/node-server',
  },
  {
    name: '@mariozechner/clipboard',
    version: '0.3.9',
    integrity:
      'sha512-ABnA53mdfkGZwOFUdZNv2S0CWGO/EIuPj8Vv9xmBFmSYg/qFc7ihO6q5FcQjvoE67kZpWkEc4AhD6B/os04yuA==',
    path: 'node_modules/@mariozechner/clipboard',
  },
  {
    name: '@mariozechner/clipboard-darwin-arm64',
    version: '0.3.9',
    integrity:
      'sha512-BfgV7vCEWZwJwZJw03r6bP5+tf0iI/ANuQYCxi9RNn7FrWB3yzGuMKCrNLRl6V761vXRdL8+OqZ0wd4TqlsNOQ==',
    path: 'node_modules/@mariozechner/clipboard-darwin-arm64',
    os: ['darwin'],
    cpu: ['arm64'],
  },
  {
    name: '@mariozechner/clipboard-darwin-universal',
    version: '0.3.9',
    integrity:
      'sha512-BGGR4iA9Z2shAjI65eI5xtyb3LYNlDW9X3gxKxDbqtbnREohsrqznov6zpKoIrsRWpzlYVEdKphS7ksJ0/ndSQ==',
    path: 'node_modules/@mariozechner/clipboard-darwin-universal',
    os: ['darwin'],
  },
  {
    name: '@mariozechner/clipboard-darwin-x64',
    version: '0.3.9',
    integrity:
      'sha512-4kURmCbS6nt8uYhtmWpUcJWyPHfmAr5dTpXD1nO3pIfa+TSQ9DbrGOYCKH+aEFW47XhQ4Vp8ZTszie+wfFvDKg==',
    path: 'node_modules/@mariozechner/clipboard-darwin-x64',
    os: ['darwin'],
    cpu: ['x64'],
  },
  {
    name: '@mariozechner/clipboard-linux-arm64-gnu',
    version: '0.3.9',
    integrity:
      'sha512-g59OkUGP2DDfCOIKypHeYgv2M55u/cKvXa5dSxFbEJ34XvIQMdcVmpKCkGUro3ZgefXiGVdwguvTMQGpHWzIXw==',
    path: 'node_modules/@mariozechner/clipboard-linux-arm64-gnu',
    os: ['linux'],
    cpu: ['arm64'],
  },
  {
    name: '@mariozechner/clipboard-linux-arm64-musl',
    version: '0.3.9',
    integrity:
      'sha512-AGuJdgKsmJdm4Pych7kv3sqe591ERRaAHW3xjLooiFzn8J+PxUyof++7YZrB5Y5tpnTO+K18Og3taj2NpluCRQ==',
    path: 'node_modules/@mariozechner/clipboard-linux-arm64-musl',
    os: ['linux'],
    cpu: ['arm64'],
  },
  {
    name: '@mariozechner/clipboard-linux-riscv64-gnu',
    version: '0.3.9',
    integrity:
      'sha512-DXBEAiuMpk7dhS1a9NzNxVAFi1vaKoPu7rQNgY8LIDLGrK3lnIp3nT10DUum+PKVJoJppIP+NAA8IZe4DMNDPw==',
    path: 'node_modules/@mariozechner/clipboard-linux-riscv64-gnu',
    os: ['linux'],
    cpu: ['riscv64'],
  },
  {
    name: '@mariozechner/clipboard-linux-x64-gnu',
    version: '0.3.9',
    integrity:
      'sha512-WORrMLd6EpElEME7JRKfSaY34nW1P5LbdgK5YNCS1ncG2LqmITsSMEJ8nh2mpvxb3TxqbOOKgY7k9eMJYlW9Mw==',
    path: 'node_modules/@mariozechner/clipboard-linux-x64-gnu',
    os: ['linux'],
    cpu: ['x64'],
  },
  {
    name: '@mariozechner/clipboard-linux-x64-musl',
    version: '0.3.9',
    integrity:
      'sha512-/DHn+1DrfL6oRaPPWXaOKvonFFrni666fxd+zFqiQEfvBH0tsHVWjq9iqBk0oDp0qaPA72lIMy5BptxISBEhZQ==',
    path: 'node_modules/@mariozechner/clipboard-linux-x64-musl',
    os: ['linux'],
    cpu: ['x64'],
  },
  {
    name: '@mariozechner/clipboard-win32-arm64-msvc',
    version: '0.3.9',
    integrity:
      'sha512-O5FHD3ErkMwMhNzAfu3ggy0ug4z7btZuoQgwwxlzPrwV2bxlD6WDpqBY4NCgICAgZdDKdp+loUEKVAVt8aYnhQ==',
    path: 'node_modules/@mariozechner/clipboard-win32-arm64-msvc',
    os: ['win32'],
    cpu: ['arm64'],
  },
  {
    name: '@mariozechner/clipboard-win32-x64-msvc',
    version: '0.3.9',
    integrity:
      'sha512-ihQC3EufqEY81vhXBgVBtK4prL+wc62zJsSvxrgz7K1hsdt6OObz6v9p3Rn1OG3GJksTTKMJF0u/guMISHPhSA==',
    path: 'node_modules/@mariozechner/clipboard-win32-x64-msvc',
    os: ['win32'],
    cpu: ['x64'],
  },
  {
    name: '@mistralai/mistralai',
    version: '2.2.6',
    integrity:
      'sha512-W8pX7zHxjJvMIpw8JMxeJEleapXX0Q9NPszdNzqkM3MIEoIGPObdodujj+WHteXEvGfaP/AMwlNyRfEzSY6dQQ==',
    path: 'node_modules/@mistralai/mistralai',
  },
  {
    name: '@modelcontextprotocol/sdk',
    version: '1.29.0',
    integrity:
      'sha512-zo37mZA9hJWpULgkRpowewez1y6ML5GsXJPY8FI0tBBCd77HEvza4jDqRKOXgHNn867PVGCyTdzqpz0izu5ZjQ==',
    path: 'node_modules/@modelcontextprotocol/sdk',
  },
  {
    name: 'content-type',
    version: '1.0.5',
    integrity:
      'sha512-nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==',
    path: 'node_modules/@modelcontextprotocol/sdk/node_modules/content-type',
  },
  {
    name: '@nodable/entities',
    version: '2.2.0',
    integrity:
      'sha512-9uGyhaQavEUMC8AIddIjau4NsnsXhou+j5sBAGojCM1oxmQpVKTWR/9JxABD6UAv12vpIms55fPZKFQEhG6uBg==',
    path: 'node_modules/@nodable/entities',
  },
  {
    name: '@opentelemetry/api',
    version: '1.9.0',
    integrity:
      'sha512-3giAOQvZiH5F9bMlMiv8+GSPMeqg0dbaeo58/0SlA9sxSqZhnUtxzX9/2FzyhS9sWQf5S0GJE0AKBrFqjpeYcg==',
    path: 'node_modules/@opentelemetry/api',
  },
  {
    name: '@opentelemetry/semantic-conventions',
    version: '1.41.1',
    integrity:
      'sha512-/UhIkaZgPutTFmQ7RnIJGgDXZmtEJ7Dvi86xNTFWcnRxVRNk/aotsqDJYeEvDP+FSMB2SdW+pQzNMcWP0rwuNA==',
    path: 'node_modules/@opentelemetry/semantic-conventions',
  },
  {
    name: '@protobufjs/aspromise',
    version: '1.1.2',
    integrity:
      'sha512-j+gKExEuLmKwvz3OgROXtrJ2UG2x8Ch2YZUxahh+s1F2HZ+wAceUNLkvy6zKCPVRkU++ZWQrdxsUeQXmcg4uoQ==',
    path: 'node_modules/@protobufjs/aspromise',
  },
  {
    name: '@protobufjs/base64',
    version: '1.1.2',
    integrity:
      'sha512-AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==',
    path: 'node_modules/@protobufjs/base64',
  },
  {
    name: '@protobufjs/codegen',
    version: '2.0.5',
    integrity:
      'sha512-zgXFLzW3Ap33e6d0Wlj4MGIm6Ce8O89n/apUaGNB/jx+hw+ruWEp7EwGUshdLKVRCxZW12fp9r40E1mQrf/34g==',
    path: 'node_modules/@protobufjs/codegen',
  },
  {
    name: '@protobufjs/eventemitter',
    version: '1.1.1',
    integrity:
      'sha512-vW1GmwMZNnL+gMRaovlh9yZX74kc+TTU3FObkkurpMaRtBfLP3ldjS9KQWlwZgraRE0+dheEEoAxdzcJQ8eXZg==',
    path: 'node_modules/@protobufjs/eventemitter',
  },
  {
    name: '@protobufjs/fetch',
    version: '1.1.1',
    integrity:
      'sha512-GpptLrs57adMSuHi3VNj0mAF8dwh36LMaYF6XyJ6JMWlVsc+t42tm1HSEDmOs3A8fC9yyeisgLhsTVQokOZ0zw==',
    path: 'node_modules/@protobufjs/fetch',
  },
  {
    name: '@protobufjs/float',
    version: '1.0.2',
    integrity:
      'sha512-Ddb+kVXlXst9d+R9PfTIxh1EdNkgoRe5tOX6t01f1lYWOvJnSPDBlG241QLzcyPdoNTsblLUdujGSE4RzrTZGQ==',
    path: 'node_modules/@protobufjs/float',
  },
  {
    name: '@protobufjs/path',
    version: '1.1.2',
    integrity:
      'sha512-6JOcJ5Tm08dOHAbdR3GrvP+yUUfkjG5ePsHYczMFLq3ZmMkAD98cDgcT2iA1lJ9NVwFd4tH/iSSoe44YWkltEA==',
    path: 'node_modules/@protobufjs/path',
  },
  {
    name: '@protobufjs/pool',
    version: '1.1.0',
    integrity:
      'sha512-0kELaGSIDBKvcgS4zkjz1PeddatrjYcmMWOlAuAPwAeccUrPHdUqo/J6LiymHHEiJT5NrF1UVwxY14f+fy4WQw==',
    path: 'node_modules/@protobufjs/pool',
  },
  {
    name: '@protobufjs/utf8',
    version: '1.1.1',
    integrity:
      'sha512-oOAWABowe8EAbMyWKM0tYDKi8Yaox52D+HWZhAIJqQXbqe0xI/GV7FhLWqlEKreMkfDjshR5FKgi3mnle0h6Eg==',
    path: 'node_modules/@protobufjs/utf8',
  },
  {
    name: '@silvia-odwyer/photon-node',
    version: '0.3.4',
    integrity:
      'sha512-bnly4BKB3KDTFxrUIcgCLbaeVVS8lrAkri1pEzskpmxu9MdfGQTy8b8EgcD83ywD3RPMsIulY8xJH5Awa+t9fA==',
    path: 'node_modules/@silvia-odwyer/photon-node',
  },
  {
    name: '@smithy/core',
    version: '3.25.0',
    integrity:
      'sha512-TTD6el7tvKyafkXBf7XO3jLOE+qVxOTrLjp/fEGiV3BMfUHK/LfdYlQO9YgZvzxC7kqA3H/IhJXNqQgnbgjb7A==',
    path: 'node_modules/@smithy/core',
  },
  {
    name: '@smithy/credential-provider-imds',
    version: '4.4.0',
    integrity:
      'sha512-pPQmNdEvMJttv9z2kdYxoui83p/nr32zjMf0aMfmzmGmFEgKXUfy0vXiNg0fx4R5XLQzmJBLM9Wg0guEq2/q8A==',
    path: 'node_modules/@smithy/credential-provider-imds',
  },
  {
    name: '@smithy/fetch-http-handler',
    version: '5.5.0',
    integrity:
      'sha512-OG8kBYAgX7lf32+xLzgirvuLffn1KNoszaSiButt45i2cRa5irk8LQXLYQ5Smij1SBTN4KMNcBsRwRrLPfIGyA==',
    path: 'node_modules/@smithy/fetch-http-handler',
  },
  {
    name: '@smithy/is-array-buffer',
    version: '2.2.0',
    integrity:
      'sha512-GGP3O9QFD24uGeAXYUjwSTXARoqpZykHadOmA8G5vfJPK0/DC67qa//0qvqrJzL1xc8WQWX7/yc7fwudjPHPhA==',
    path: 'node_modules/@smithy/is-array-buffer',
  },
  {
    name: '@smithy/node-http-handler',
    version: '4.8.0',
    integrity:
      'sha512-Mq7TNt/VhlEWiYRLQGpzUWeUxh899UGpjKh7Ru0WVIDIjnE+cTRAn0NYlFQ6bWfsQnKnpCbWJj86HzmcG0qEdg==',
    path: 'node_modules/@smithy/node-http-handler',
  },
  {
    name: '@smithy/signature-v4',
    version: '5.5.0',
    integrity:
      'sha512-vW6UdK7e7gV2wU/tXRsPq4pMQMusb8VymdVOyIFNA1FtyRmEClRFkYDtYI8UcO/HM0wK3qqjvvQs3HOlbgMbdg==',
    path: 'node_modules/@smithy/signature-v4',
  },
  {
    name: '@smithy/types',
    version: '4.15.0',
    integrity:
      'sha512-Z5TAOxygoFvybJV3igo5SloFflSokHx2hu1eFA+DxDTcn+FtKxUSui+rbTRG1pAafMA888Z3MVvCWUuvCrTXjg==',
    path: 'node_modules/@smithy/types',
  },
  {
    name: '@smithy/util-buffer-from',
    version: '2.2.0',
    integrity:
      'sha512-IJdWBbTcMQ6DA0gdNhh/BwrLkDR+ADW5Kr1aZmd4k3DIF6ezMV4R2NIAmT08wQJ3yUK82thHWmC/TnK/wpMMIA==',
    path: 'node_modules/@smithy/util-buffer-from',
  },
  {
    name: '@smithy/util-utf8',
    version: '2.3.0',
    integrity:
      'sha512-R8Rdn8Hy72KKcebgLiv8jQcQkXoLMOGGv5uI1/k0l+snqkOzQ1R0ChUBCxWMlBsFMekWjq0wRudIweFs7sKT5A==',
    path: 'node_modules/@smithy/util-utf8',
  },
  {
    name: '@types/node',
    version: '26.0.1',
    integrity:
      'sha512-fc3KiUoBt6kie0N9bIW3E47vZsuaMf0PM2AaUpLCLT0s/LvX1nxAim6Fc049cNxODPpGm6qRAuUOB86SkRuPQw==',
    path: 'node_modules/@types/node',
  },
  {
    name: '@types/retry',
    version: '0.12.0',
    integrity:
      'sha512-wWKOClTTiizcZhXnPY4wikVAwmdYHp8q6DmC+EJUzAMsycb7HB32Kh9RN4+0gExjmPmZSAQjgURXIGATPegAvA==',
    path: 'node_modules/@types/retry',
  },
  {
    name: 'accepts',
    version: '2.0.0',
    integrity:
      'sha512-5cvg6CtKwfgdmVqY1WIiXKc3Q1bkRqGLi+2W/6ao+6Y7gu/RCwRuAhGEzh5B4KlszSuTLgZYuqFqo5bImjNKng==',
    path: 'node_modules/accepts',
  },
  {
    name: 'agent-base',
    version: '7.1.4',
    integrity:
      'sha512-MnA+YT8fwfJPgBx3m60MNqakm30XOkyIoH1y6huTQvC0PwZG7ki8NacLBcrPbNoo8vEZy7Jpuk7+jMO+CUovTQ==',
    path: 'node_modules/agent-base',
  },
  {
    name: 'ajv',
    version: '8.20.0',
    integrity:
      'sha512-Thbli+OlOj+iMPYFBVBfJ3OmCAnaSyNn4M1vz9T6Gka5Jt9ba/HIR56joy65tY6kx/FCF5VXNB819Y7/GUrBGA==',
    path: 'node_modules/ajv',
  },
  {
    name: 'ajv-formats',
    version: '3.0.1',
    integrity:
      'sha512-8iUql50EUR+uUcdRQ3HDqa6EVyo3docL8g5WJ3FNcWmu62IbkGUue/pEyLBW8VGKKucTPgqeks4fIU1DA4yowQ==',
    path: 'node_modules/ajv-formats',
  },
  {
    name: 'anynum',
    version: '1.0.0',
    integrity:
      'sha512-xjR9/zBVnUOP6ztMIIgShjsxui80nQUQH+5xJnvrYLs+90bF25/KJqaAi8mk+B4RDtX1Nspi6fmp4YTEts8SfA==',
    path: 'node_modules/anynum',
  },
  {
    name: 'balanced-match',
    version: '4.0.4',
    integrity:
      'sha512-BLrgEcRTwX2o6gGxGOCNyMvGSp35YofuYzw9h1IMTRmKqttAZZVU67bdb9Pr2vUHA8+j3i2tJfjO6C6+4myGTA==',
    path: 'node_modules/balanced-match',
  },
  {
    name: 'base64-js',
    version: '1.5.1',
    integrity:
      'sha512-AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==',
    path: 'node_modules/base64-js',
  },
  {
    name: 'bignumber.js',
    version: '9.3.1',
    integrity:
      'sha512-Ko0uX15oIUS7wJ3Rb30Fs6SkVbLmPBAKdlm7q9+ak9bbIeFf0MwuBsQV6z7+X768/cHsfg+WlysDWJcmthjsjQ==',
    path: 'node_modules/bignumber.js',
  },
  {
    name: 'body-parser',
    version: '2.3.0',
    integrity:
      'sha512-2cGmJupaNgg+QUwVLAucDuWuoMZ6EX9iHDRswZ5lsNYEmwPaRknMPCLZz07yTzVq/83p4o/wzbDZbBrTvGGTIw==',
    path: 'node_modules/body-parser',
  },
  {
    name: 'bowser',
    version: '2.14.1',
    integrity:
      'sha512-tzPjzCxygAKWFOJP011oxFHs57HzIhOEracIgAePE4pqB3LikALKnSzUyU4MGs9/iCEUuHlAJTjTc5M+u7YEGg==',
    path: 'node_modules/bowser',
  },
  {
    name: 'brace-expansion',
    version: '5.0.7',
    integrity:
      'sha512-7oFy703dxfY3/NLxC1fh2SUCQ0H9rmAY+5EpDVfXjUTTs+HEwR2nYaqLv+GWcTsumwxPfiz6CzCNkwXwBUwqCA==',
    path: 'node_modules/brace-expansion',
  },
  {
    name: 'buffer-equal-constant-time',
    version: '1.0.1',
    integrity:
      'sha512-zRpUiDwd/xk6ADqPMATG8vc9VPrkck7T07OIx0gnjmJAnHnTVXNQG3vfvWNuiZIkwu9KrKdA1iJKfsfTVxE6NA==',
    path: 'node_modules/buffer-equal-constant-time',
  },
  {
    name: 'bytes',
    version: '3.1.2',
    integrity:
      'sha512-/Nf7TyzTx6S3yRJObOAV7956r8cr2+Oj8AC5dt8wSP3BQAoeX58NoHyCU8P8zGkNXStjTSi6fzO6F0pBdcYbEg==',
    path: 'node_modules/bytes',
  },
  {
    name: 'call-bind-apply-helpers',
    version: '1.0.2',
    integrity:
      'sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==',
    path: 'node_modules/call-bind-apply-helpers',
  },
  {
    name: 'call-bound',
    version: '1.0.4',
    integrity:
      'sha512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==',
    path: 'node_modules/call-bound',
  },
  {
    name: 'chalk',
    version: '5.6.2',
    integrity:
      'sha512-7NzBL0rN6fMUW+f7A6Io4h40qQlG+xGmtMxfbnH/K7TAtt8JQWVQK+6g0UXKMeVJoyV5EkkNsErQ8pVD3bLHbA==',
    path: 'node_modules/chalk',
  },
  {
    name: 'content-disposition',
    version: '1.1.0',
    integrity:
      'sha512-5jRCH9Z/+DRP7rkvY83B+yGIGX96OYdJmzngqnw2SBSxqCFPd0w2km3s5iawpGX8krnwSGmF0FW5Nhr0Hfai3g==',
    path: 'node_modules/content-disposition',
  },
  {
    name: 'content-type',
    version: '2.0.0',
    integrity:
      'sha512-j/O/d7GcZCyNl7/hwZAb606rzqkyvaDctLmckbxLzHvFBzTJHuGEdodATcP3yIRoDrLHkIATJuvzbFlp/ki2cQ==',
    path: 'node_modules/content-type',
  },
  {
    name: 'cookie',
    version: '0.7.2',
    integrity:
      'sha512-yki5XnKuf750l50uGTllt6kKILY4nQ1eNIQatoXEByZ5dWgnKqbnqmTrBE5B4N7lrMJKQ2ytWMiTO2o0v6Ew/w==',
    path: 'node_modules/cookie',
  },
  {
    name: 'cookie-signature',
    version: '1.2.2',
    integrity:
      'sha512-D76uU73ulSXrD1UXF4KE2TMxVVwhsnCgfAyTg9k8P6KGZjlXKrOLe4dJQKI3Bxi5wjesZoFXJWElNWBjPZMbhg==',
    path: 'node_modules/cookie-signature',
  },
  {
    name: 'cors',
    version: '2.8.6',
    integrity:
      'sha512-tJtZBBHA6vjIAaF6EnIaq6laBBP9aq/Y3ouVJjEfoHbRBcHBAHYcMh/w8LDrk2PvIMMq8gmopa5D4V8RmbrxGw==',
    path: 'node_modules/cors',
  },
  {
    name: 'cross-spawn',
    version: '7.0.6',
    integrity:
      'sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==',
    path: 'node_modules/cross-spawn',
  },
  {
    name: 'data-uri-to-buffer',
    version: '4.0.1',
    integrity:
      'sha512-0R9ikRb668HB7QDxT1vkpuUBtqc53YyAwMwGeUFKRojY/NWKvdZ+9UYtRfGmhqNbRkTSVpMbmyhXipFFv2cb/A==',
    path: 'node_modules/data-uri-to-buffer',
  },
  {
    name: 'debug',
    version: '4.4.3',
    integrity:
      'sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==',
    path: 'node_modules/debug',
  },
  {
    name: 'depd',
    version: '2.0.0',
    integrity:
      'sha512-g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==',
    path: 'node_modules/depd',
  },
  {
    name: 'diff',
    version: '8.0.4',
    integrity:
      'sha512-DPi0FmjiSU5EvQV0++GFDOJ9ASQUVFh5kD+OzOnYdi7n3Wpm9hWWGfB/O2blfHcMVTL5WkQXSnRiK9makhrcnw==',
    path: 'node_modules/diff',
  },
  {
    name: 'dunder-proto',
    version: '1.0.1',
    integrity:
      'sha512-KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==',
    path: 'node_modules/dunder-proto',
  },
  {
    name: 'ecdsa-sig-formatter',
    version: '1.0.11',
    integrity:
      'sha512-nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==',
    path: 'node_modules/ecdsa-sig-formatter',
  },
  {
    name: 'ee-first',
    version: '1.1.1',
    integrity:
      'sha512-WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==',
    path: 'node_modules/ee-first',
  },
  {
    name: 'encodeurl',
    version: '2.0.0',
    integrity:
      'sha512-Q0n9HRi4m6JuGIV1eFlmvJB7ZEVxu93IrMyiMsGC0lrMJMWzRgx6WGquyfQgZVb31vhGgXnfmPNNXmxnOkRBrg==',
    path: 'node_modules/encodeurl',
  },
  {
    name: 'es-define-property',
    version: '1.0.1',
    integrity:
      'sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==',
    path: 'node_modules/es-define-property',
  },
  {
    name: 'es-errors',
    version: '1.3.0',
    integrity:
      'sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==',
    path: 'node_modules/es-errors',
  },
  {
    name: 'es-object-atoms',
    version: '1.1.2',
    integrity:
      'sha512-HWcBoN6NileqtSydK2FqHbS/LoDd2pqrnQHLyJzBj4kOp/ky2MWMN694xOfkK8/SnUsW2DH7EfyVlydKCsm1Zw==',
    path: 'node_modules/es-object-atoms',
  },
  {
    name: 'escape-html',
    version: '1.0.3',
    integrity:
      'sha512-NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==',
    path: 'node_modules/escape-html',
  },
  {
    name: 'etag',
    version: '1.8.1',
    integrity:
      'sha512-aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==',
    path: 'node_modules/etag',
  },
  {
    name: 'eventsource',
    version: '3.0.7',
    integrity:
      'sha512-CRT1WTyuQoD771GW56XEZFQ/ZoSfWid1alKGDYMmkt2yl8UXrVR4pspqWNEcqKvVIzg6PAltWjxcSSPrboA4iA==',
    path: 'node_modules/eventsource',
  },
  {
    name: 'eventsource-parser',
    version: '3.1.0',
    integrity:
      'sha512-kJezFj9YFAMLeORyi7aCLxLbD5/qWMQnoMVlVPyHIll7lgRJCc3JVln9Vgl9nwQi0YkMnhdGTMNn7CkRRAptMg==',
    path: 'node_modules/eventsource-parser',
  },
  {
    name: 'express',
    version: '5.2.1',
    integrity:
      'sha512-hIS4idWWai69NezIdRt2xFVofaF4j+6INOpJlVOLDO8zXGpUVEVzIYk12UUi2JzjEzWL3IOAxcTubgz9Po0yXw==',
    path: 'node_modules/express',
  },
  {
    name: 'express-rate-limit',
    version: '8.5.2',
    integrity:
      'sha512-5Kb34ipNX694DH48vN9irak1Qx30nb0PLYHXfJgw4YEjiC3ZEmZJhwOp+VfiCYwFzvFTdB9QkArYS5kXa2cx2A==',
    path: 'node_modules/express-rate-limit',
  },
  {
    name: 'content-type',
    version: '1.0.5',
    integrity:
      'sha512-nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==',
    path: 'node_modules/express/node_modules/content-type',
  },
  {
    name: 'extend',
    version: '3.0.2',
    integrity:
      'sha512-fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==',
    path: 'node_modules/extend',
  },
  {
    name: 'fast-deep-equal',
    version: '3.1.3',
    integrity:
      'sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==',
    path: 'node_modules/fast-deep-equal',
  },
  {
    name: 'fast-uri',
    version: '3.1.3',
    integrity:
      'sha512-i70LwGWUduXqzicKXWshooq+sWL1K3WUU5rKZNG/0i3a1OSoX3HqhH5WbWwTmqWfor4urUakGPiRQcleRZTwOg==',
    path: 'node_modules/fast-uri',
  },
  {
    name: 'fast-xml-builder',
    version: '1.2.0',
    integrity:
      'sha512-00aAWieqff+ZJhsXA4g1g7M8k+7AYoMUUHF+/zFb5U6Uv/P0Vl4QZo84/IcufzYalLuEj9928bXN9PbbFzMF0Q==',
    path: 'node_modules/fast-xml-builder',
  },
  {
    name: 'fast-xml-parser',
    version: '5.7.3',
    integrity:
      'sha512-C0AaNuC+mscy6vrAQKAc/rMq+zAPHodfHGZu4sGVehvAQt/JLG1O5zEcYcXSY5zSqr4YVgxsB+pHXTq0i7eDlg==',
    path: 'node_modules/fast-xml-parser',
  },
  {
    name: 'fetch-blob',
    version: '3.2.0',
    integrity:
      'sha512-7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==',
    path: 'node_modules/fetch-blob',
  },
  {
    name: 'finalhandler',
    version: '2.1.1',
    integrity:
      'sha512-S8KoZgRZN+a5rNwqTxlZZePjT/4cnm0ROV70LedRHZ0p8u9fRID0hJUZQpkKLzro8LfmC8sx23bY6tVNxv8pQA==',
    path: 'node_modules/finalhandler',
  },
  {
    name: 'formdata-polyfill',
    version: '4.0.10',
    integrity:
      'sha512-buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==',
    path: 'node_modules/formdata-polyfill',
  },
  {
    name: 'forwarded',
    version: '0.2.0',
    integrity:
      'sha512-buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==',
    path: 'node_modules/forwarded',
  },
  {
    name: 'fresh',
    version: '2.0.0',
    integrity:
      'sha512-Rx/WycZ60HOaqLKAi6cHRKKI7zxWbJ31MhntmtwMoaTeF7XFH9hhBp8vITaMidfljRQ6eYWCKkaTK+ykVJHP2A==',
    path: 'node_modules/fresh',
  },
  {
    name: 'function-bind',
    version: '1.1.2',
    integrity:
      'sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==',
    path: 'node_modules/function-bind',
  },
  {
    name: 'gaxios',
    version: '7.1.5',
    integrity:
      'sha512-5FZy72Rh8LhtjmvDrKkI+lVhrsQrVKVsItxMoDm5mNQE+xR0WVIIs+jzPSJgBvKVsLi24fZhXJIsNI0bihDzFg==',
    path: 'node_modules/gaxios',
  },
  {
    name: 'gcp-metadata',
    version: '8.1.2',
    integrity:
      'sha512-zV/5HKTfCeKWnxG0Dmrw51hEWFGfcF2xiXqcA3+J90WDuP0SvoiSO5ORvcBsifmx/FoIjgQN3oNOGaQ5PhLFkg==',
    path: 'node_modules/gcp-metadata',
  },
  {
    name: 'get-east-asian-width',
    version: '1.6.0',
    integrity:
      'sha512-QRbvDIbx6YklUe6RxeTeleMR0yv3cYH6PsPZHcnVn7xv7zO1BHN8r0XETu8n6Ye3Q+ahtSarc3WgtNWmehIBfA==',
    path: 'node_modules/get-east-asian-width',
  },
  {
    name: 'get-intrinsic',
    version: '1.3.0',
    integrity:
      'sha512-9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==',
    path: 'node_modules/get-intrinsic',
  },
  {
    name: 'get-proto',
    version: '1.0.1',
    integrity:
      'sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==',
    path: 'node_modules/get-proto',
  },
  {
    name: 'glob',
    version: '13.0.6',
    integrity:
      'sha512-Wjlyrolmm8uDpm/ogGyXZXb1Z+Ca2B8NbJwqBVg0axK9GbBeoS7yGV6vjXnYdGm6X53iehEuxxbyiKp8QmN4Vw==',
    path: 'node_modules/glob',
  },
  {
    name: 'google-auth-library',
    version: '10.7.0',
    integrity:
      'sha512-QpTAbNJ36TliZLx3TTtahR8HG0hN9RllL1e3FymOvQSIKK8JmgV58H924ub2wa2DsS3ANjjP1Aw1N+Ramc8hqQ==',
    path: 'node_modules/google-auth-library',
  },
  {
    name: 'google-logging-utils',
    version: '1.1.3',
    integrity:
      'sha512-eAmLkjDjAFCVXg7A1unxHsLf961m6y17QFqXqAXGj/gVkKFrEICfStRfwUlGNfeCEjNRa32JEWOUTlYXPyyKvA==',
    path: 'node_modules/google-logging-utils',
  },
  {
    name: 'gopd',
    version: '1.2.0',
    integrity:
      'sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==',
    path: 'node_modules/gopd',
  },
  {
    name: 'graceful-fs',
    version: '4.2.11',
    integrity:
      'sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==',
    path: 'node_modules/graceful-fs',
  },
  {
    name: 'has-symbols',
    version: '1.1.0',
    integrity:
      'sha512-1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==',
    path: 'node_modules/has-symbols',
  },
  {
    name: 'hasown',
    version: '2.0.4',
    integrity:
      'sha512-T2UbfbBEF32wiepXIsMlTW9+dDYC6wMh/t/vYA4tuOMKqWz/n3vr1NFSxQiyP+zk2mXsoMA/i/7qV6LKut1t1A==',
    path: 'node_modules/hasown',
  },
  {
    name: 'highlight.js',
    version: '10.7.3',
    integrity:
      'sha512-tzcUFauisWKNHaRkN4Wjl/ZA07gENAjFl3J/c480dprkGTg5EQstgaNFqBfUqCq54kZRIEcreTsAgF/m2quD7A==',
    path: 'node_modules/highlight.js',
  },
  {
    name: 'hono',
    version: '4.12.27',
    integrity:
      'sha512-1yrb/+w6HWQJrUCLkJ2IF5jNIPvvFkblV5RNOYl6bV+OA6p9GLcMpHFFGTosSvHvcAUibuUukRqhlYI4z32C7Q==',
    path: 'node_modules/hono',
  },
  {
    name: 'hosted-git-info',
    version: '9.0.3',
    integrity:
      'sha512-Hc+ghLoSt6QaYZUv0WBiIvmMDZuZZ7oaDvdH8MbfOO4lOsxdXLEvuC6ePoGs9H1X9oCLyq6+NVN0MKqD+ydxyg==',
    path: 'node_modules/hosted-git-info',
  },
  {
    name: 'http-errors',
    version: '2.0.1',
    integrity:
      'sha512-4FbRdAX+bSdmo4AUFuS0WNiPz8NgFt+r8ThgNWmlrjQjt1Q7ZR9+zTlce2859x4KSXrwIsaeTqDoKQmtP8pLmQ==',
    path: 'node_modules/http-errors',
  },
  {
    name: 'http-proxy-agent',
    version: '7.0.2',
    integrity:
      'sha512-T1gkAiYYDWYx3V5Bmyu7HcfcvL7mUrTWiM6yOfa3PIphViJ/gFPbvidQ+veqSOHci/PxBcDabeUNCzpOODJZig==',
    path: 'node_modules/http-proxy-agent',
  },
  {
    name: 'https-proxy-agent',
    version: '7.0.6',
    integrity:
      'sha512-vK9P5/iUfdl95AI+JVyUuIcVtd4ofvtrOr3HNtM2yxC9bnMbEdp3x01OhQNnjb8IJYi38VlTE3mBXwcfvywuSw==',
    path: 'node_modules/https-proxy-agent',
  },
  {
    name: 'iconv-lite',
    version: '0.7.2',
    integrity:
      'sha512-im9DjEDQ55s9fL4EYzOAv0yMqmMBSZp6G0VvFyTMPKWxiSBHUj9NW/qqLmXUwXrrM7AvqSlTCfvqRb0cM8yYqw==',
    path: 'node_modules/iconv-lite',
  },
  {
    name: 'ignore',
    version: '7.0.5',
    integrity:
      'sha512-Hs59xBNfUIunMFgWAbGX5cq6893IbWg4KnrjbYwX3tx0ztorVgTDA6B2sxf8ejHJ4wz8BqGUMYlnzNBer5NvGg==',
    path: 'node_modules/ignore',
  },
  {
    name: 'inherits',
    version: '2.0.4',
    integrity:
      'sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==',
    path: 'node_modules/inherits',
  },
  {
    name: 'ip-address',
    version: '10.2.0',
    integrity:
      'sha512-/+S6j4E9AHvW9SWMSEY9Xfy66O5PWvVEJ08O0y5JGyEKQpojb0K0GKpz/v5HJ/G0vi3D2sjGK78119oXZeE0qA==',
    path: 'node_modules/ip-address',
  },
  {
    name: 'ipaddr.js',
    version: '1.9.1',
    integrity:
      'sha512-0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==',
    path: 'node_modules/ipaddr.js',
  },
  {
    name: 'is-promise',
    version: '4.0.0',
    integrity:
      'sha512-hvpoI6korhJMnej285dSg6nu1+e6uxs7zG3BYAm5byqDsgJNWwxzM6z6iZiAgQR4TJ30JmBTOwqZUw3WlyH3AQ==',
    path: 'node_modules/is-promise',
  },
  {
    name: 'isexe',
    version: '2.0.0',
    integrity:
      'sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==',
    path: 'node_modules/isexe',
  },
  {
    name: 'jiti',
    version: '2.7.0',
    integrity:
      'sha512-AC/7JofJvZGrrneWNaEnJeOLUx+JlGt7tNa0wZiRPT4MY1wmfKjt2+6O2p2uz2+skll8OZZmJMNqeke7kKbNgQ==',
    path: 'node_modules/jiti',
  },
  {
    name: 'jose',
    version: '6.2.3',
    integrity:
      'sha512-YYVDInQKFJfR/xa3ojUTl8c2KoTwiL1R5Wg9YCydwH0x0B9grbzlg5HC7mMjCtUJjbQ/YnGEZIhI5tCgfTb4Hw==',
    path: 'node_modules/jose',
  },
  {
    name: 'json-bigint',
    version: '1.0.0',
    integrity:
      'sha512-SiPv/8VpZuWbvLSMtTDU8hEfrZWg/mH/nV/b4o0CYbSxu1UIQPLdwKOCIyLQX+VIPO5vrLX3i8qtqFyhdPSUSQ==',
    path: 'node_modules/json-bigint',
  },
  {
    name: 'json-schema-to-ts',
    version: '3.1.1',
    integrity:
      'sha512-+DWg8jCJG2TEnpy7kOm/7/AxaYoaRbjVB4LFZLySZlWn8exGs3A4OLJR966cVvU26N7X9TWxl+Jsw7dzAqKT6g==',
    path: 'node_modules/json-schema-to-ts',
  },
  {
    name: 'json-schema-traverse',
    version: '1.0.0',
    integrity:
      'sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==',
    path: 'node_modules/json-schema-traverse',
  },
  {
    name: 'json-schema-typed',
    version: '8.0.2',
    integrity:
      'sha512-fQhoXdcvc3V28x7C7BMs4P5+kNlgUURe2jmUT1T//oBRMDrqy1QPelJimwZGo7Hg9VPV3EQV5Bnq4hbFy2vetA==',
    path: 'node_modules/json-schema-typed',
  },
  {
    name: 'jwa',
    version: '2.0.1',
    integrity:
      'sha512-hRF04fqJIP8Abbkq5NKGN0Bbr3JxlQ+qhZufXVr0DvujKy93ZCbXZMHDL4EOtodSbCWxOqR8MS1tXA5hwqCXDg==',
    path: 'node_modules/jwa',
  },
  {
    name: 'jws',
    version: '4.0.1',
    integrity:
      'sha512-EKI/M/yqPncGUUh44xz0PxSidXFr/+r0pA70+gIYhjv+et7yxM+s29Y+VGDkovRofQem0fs7Uvf4+YmAdyRduA==',
    path: 'node_modules/jws',
  },
  {
    name: 'long',
    version: '5.3.2',
    integrity:
      'sha512-mNAgZ1GmyNhD7AuqnTG3/VQ26o760+ZYBPKjPvugO8+nLbYfX6TVpJPseBvopbdY+qpZ/lKUnmEc1LeZYS3QAA==',
    path: 'node_modules/long',
  },
  {
    name: 'lru-cache',
    version: '11.5.1',
    integrity:
      'sha512-RPimw/7aMdv2oqRrxKwvZXcPfwBrn/JZ2xYcY9Hus/6LaS3VOAKVWKWgNLCFSiOm1ESXinjsDlidVU7JlnCN2A==',
    path: 'node_modules/lru-cache',
  },
  {
    name: 'marked',
    version: '18.0.5',
    integrity:
      'sha512-S6GcvALHg6K4ohtu4E7x0a1AqhAjp6cV8KhLSyN9qVapnzJkusVBxZRcIU9AeYsbe6P1hKDusSbEOzGyyuce6w==',
    path: 'node_modules/marked',
  },
  {
    name: 'math-intrinsics',
    version: '1.1.0',
    integrity:
      'sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==',
    path: 'node_modules/math-intrinsics',
  },
  {
    name: 'media-typer',
    version: '1.1.0',
    integrity:
      'sha512-aisnrDP4GNe06UcKFnV5bfMNPBUw4jsLGaWwWfnH3v02GnBuXX2MCVn5RbrWo0j3pczUilYblq7fQ7Nw2t5XKw==',
    path: 'node_modules/media-typer',
  },
  {
    name: 'merge-descriptors',
    version: '2.0.0',
    integrity:
      'sha512-Snk314V5ayFLhp3fkUREub6WtjBfPdCPY1Ln8/8munuLuiYhsABgBVWsozAG+MWMbVEvcdcpbi9R7ww22l9Q3g==',
    path: 'node_modules/merge-descriptors',
  },
  {
    name: 'mime-db',
    version: '1.54.0',
    integrity:
      'sha512-aU5EJuIN2WDemCcAp2vFBfp/m4EAhWJnUNSSw0ixs7/kXbd6Pg64EmwJkNdFhB8aWt1sH2CTXrLxo/iAGV3oPQ==',
    path: 'node_modules/mime-db',
  },
  {
    name: 'mime-types',
    version: '3.0.2',
    integrity:
      'sha512-Lbgzdk0h4juoQ9fCKXW4by0UJqj+nOOrI9MJ1sSj4nI8aI2eo1qmvQEie4VD1glsS250n15LsWsYtCugiStS5A==',
    path: 'node_modules/mime-types',
  },
  {
    name: 'minimatch',
    version: '10.2.5',
    integrity:
      'sha512-MULkVLfKGYDFYejP07QOurDLLQpcjk7Fw+7jXS2R2czRQzR56yHRveU5NDJEOviH+hETZKSkIk5c+T23GjFUMg==',
    path: 'node_modules/minimatch',
  },
  {
    name: 'minipass',
    version: '7.1.3',
    integrity:
      'sha512-tEBHqDnIoM/1rXME1zgka9g6Q2lcoCkxHLuc7ODJ5BxbP5d4c2Z5cGgtXAku59200Cx7diuHTOYfSBD8n6mm8A==',
    path: 'node_modules/minipass',
  },
  {
    name: 'ms',
    version: '2.1.3',
    integrity:
      'sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==',
    path: 'node_modules/ms',
  },
  {
    name: 'negotiator',
    version: '1.0.0',
    integrity:
      'sha512-8Ofs/AUQh8MaEcrlq5xOX0CQ9ypTF5dl78mjlMNfOK08fzpgTHQRQPBxcPlEtIw0yRpws+Zo/3r+5WRby7u3Gg==',
    path: 'node_modules/negotiator',
  },
  {
    name: 'node-domexception',
    version: '1.0.0',
    integrity:
      'sha512-/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==',
    path: 'node_modules/node-domexception',
  },
  {
    name: 'node-fetch',
    version: '3.3.2',
    integrity:
      'sha512-dRB78srN/l6gqWulah9SrxeYnxeddIG30+GOqK/9OlLVyLg3HPnr6SqOWTWOXKRwC2eGYCkZ59NNuSgvSrpgOA==',
    path: 'node_modules/node-fetch',
  },
  {
    name: 'object-assign',
    version: '4.1.1',
    integrity:
      'sha512-rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==',
    path: 'node_modules/object-assign',
  },
  {
    name: 'object-inspect',
    version: '1.13.4',
    integrity:
      'sha512-W67iLl4J2EXEGTbfeHCffrjDfitvLANg0UlX3wFUUSTx92KXRFegMHUVgSqE+wvhAbi4WqjGg9czysTV2Epbew==',
    path: 'node_modules/object-inspect',
  },
  {
    name: 'on-finished',
    version: '2.4.1',
    integrity:
      'sha512-oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==',
    path: 'node_modules/on-finished',
  },
  {
    name: 'once',
    version: '1.4.0',
    integrity:
      'sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==',
    path: 'node_modules/once',
  },
  {
    name: 'openai',
    version: '6.26.0',
    integrity:
      'sha512-zd23dbWTjiJ6sSAX6s0HrCZi41JwTA1bQVs0wLQPZ2/5o2gxOJA5wh7yOAUgwYybfhDXyhwlpeQf7Mlgx8EOCA==',
    path: 'node_modules/openai',
  },
  {
    name: 'p-retry',
    version: '4.6.2',
    integrity:
      'sha512-312Id396EbJdvRONlngUx0NydfrIQ5lsYu0znKVUzVvArzEIt08V1qhtyESbGVd1FGX7UKtiFp5uwKZdM8wIuQ==',
    path: 'node_modules/p-retry',
  },
  {
    name: 'parseurl',
    version: '1.3.3',
    integrity:
      'sha512-CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==',
    path: 'node_modules/parseurl',
  },
  {
    name: 'partial-json',
    version: '0.1.7',
    integrity:
      'sha512-Njv/59hHaokb/hRUjce3Hdv12wd60MtM9Z5Olmn+nehe0QDAsRtRbJPvJ0Z91TusF0SuZRIvnM+S4l6EIP8leA==',
    path: 'node_modules/partial-json',
  },
  {
    name: 'path-expression-matcher',
    version: '1.5.0',
    integrity:
      'sha512-cbrerZV+6rvdQrrD+iGMcZFEiiSrbv9Tfdkvnusy6y0x0GKBXREFg/Y65GhIfm0tnLntThhzCnfKwp1WRjeCyQ==',
    path: 'node_modules/path-expression-matcher',
  },
  {
    name: 'path-key',
    version: '3.1.1',
    integrity:
      'sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==',
    path: 'node_modules/path-key',
  },
  {
    name: 'path-scurry',
    version: '2.0.2',
    integrity:
      'sha512-3O/iVVsJAPsOnpwWIeD+d6z/7PmqApyQePUtCndjatj/9I5LylHvt5qluFaBT3I5h3r1ejfR056c+FCv+NnNXg==',
    path: 'node_modules/path-scurry',
  },
  {
    name: 'path-to-regexp',
    version: '8.4.2',
    integrity:
      'sha512-qRcuIdP69NPm4qbACK+aDogI5CBDMi1jKe0ry5rSQJz8JVLsC7jV8XpiJjGRLLol3N+R5ihGYcrPLTno6pAdBA==',
    path: 'node_modules/path-to-regexp',
  },
  {
    name: 'pkce-challenge',
    version: '5.0.1',
    integrity:
      'sha512-wQ0b/W4Fr01qtpHlqSqspcj3EhBvimsdh0KlHhH8HRZnMsEa0ea2fTULOXOS9ccQr3om+GcGRk4e+isrZWV8qQ==',
    path: 'node_modules/pkce-challenge',
  },
  {
    name: 'proper-lockfile',
    version: '4.1.2',
    integrity:
      'sha512-TjNPblN4BwAWMXU8s9AEz4JmQxnD1NNL7bNOY/AKUzyamc379FWASUhc/K1pL2noVb+XmZKLL68cjzLsiOAMaA==',
    path: 'node_modules/proper-lockfile',
  },
  {
    name: 'retry',
    version: '0.12.0',
    integrity:
      'sha512-9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==',
    path: 'node_modules/proper-lockfile/node_modules/retry',
  },
  {
    name: 'protobufjs',
    version: '7.6.4',
    integrity:
      'sha512-RJJPTTpvFfHcWLkIa2JFWK4XvtSzS0yEWDmunqHXli1h3JlkbcQZXDZdcWxv+JK3Xsl5/UFDPZ0iGm7DAengYw==',
    path: 'node_modules/protobufjs',
  },
  {
    name: 'proxy-addr',
    version: '2.0.7',
    integrity:
      'sha512-llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==',
    path: 'node_modules/proxy-addr',
  },
  {
    name: 'qs',
    version: '6.15.3',
    integrity:
      'sha512-O9gl3zCl5h5blw1KGUzQKhA5oUXSl8rwUIM5o0S3nCXMliSvy5Dzx7/DJcI+SwgICv+IneSZwhBh1oSyEHA71A==',
    path: 'node_modules/qs',
  },
  {
    name: 'range-parser',
    version: '1.3.0',
    integrity:
      'sha512-hek2mFQpPuI4E1BBKrSto+BU3e3x4xuarsbiwr3+lf7p44juvFMV0XFWQAP3xUyqXA4RrXLIoaSUGbSt056ZMw==',
    path: 'node_modules/range-parser',
  },
  {
    name: 'raw-body',
    version: '3.0.2',
    integrity:
      'sha512-K5zQjDllxWkf7Z5xJdV0/B0WTNqx6vxG70zJE4N0kBs4LovmEYWJzQGxC9bS9RAKu3bgM40lrd5zoLJ12MQ5BA==',
    path: 'node_modules/raw-body',
  },
  {
    name: 'require-from-string',
    version: '2.0.2',
    integrity:
      'sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==',
    path: 'node_modules/require-from-string',
  },
  {
    name: 'retry',
    version: '0.13.1',
    integrity:
      'sha512-XQBQ3I8W1Cge0Seh+6gjj03LbmRFWuoszgK9ooCpwYIrhhoO80pfq4cUkU5DkknwfOfFteRwlZ56PYOGYyFWdg==',
    path: 'node_modules/retry',
  },
  {
    name: 'router',
    version: '2.2.0',
    integrity:
      'sha512-nLTrUKm2UyiL7rlhapu/Zl45FwNgkZGaCpZbIHajDYgwlJCOzLSk+cIPAnsEqV955GjILJnKbdQC1nVPz+gAYQ==',
    path: 'node_modules/router',
  },
  {
    name: 'safe-buffer',
    version: '5.2.1',
    integrity:
      'sha512-rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==',
    path: 'node_modules/safe-buffer',
  },
  {
    name: 'safer-buffer',
    version: '2.1.2',
    integrity:
      'sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==',
    path: 'node_modules/safer-buffer',
  },
  {
    name: 'semver',
    version: '7.8.0',
    integrity:
      'sha512-AcM7dV/5ul4EekoQ29Agm5vri8JNqRyj39o0qpX6vDF2GZrtutZl5RwgD1XnZjiTAfncsJhMI48QQH3sN87YNA==',
    path: 'node_modules/semver',
  },
  {
    name: 'send',
    version: '1.2.1',
    integrity:
      'sha512-1gnZf7DFcoIcajTjTwjwuDjzuz4PPcY2StKPlsGAQ1+YH20IRVrBaXSWmdjowTJ6u8Rc01PoYOGHXfP1mYcZNQ==',
    path: 'node_modules/send',
  },
  {
    name: 'serve-static',
    version: '2.2.1',
    integrity:
      'sha512-xRXBn0pPqQTVQiC8wyQrKs2MOlX24zQ0POGaj0kultvoOCstBQM5yvOhAVSUwOMjQtTvsPWoNCHfPGwaaQJhTw==',
    path: 'node_modules/serve-static',
  },
  {
    name: 'setprototypeof',
    version: '1.2.0',
    integrity:
      'sha512-E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==',
    path: 'node_modules/setprototypeof',
  },
  {
    name: 'shebang-command',
    version: '2.0.0',
    integrity:
      'sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==',
    path: 'node_modules/shebang-command',
  },
  {
    name: 'shebang-regex',
    version: '3.0.0',
    integrity:
      'sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==',
    path: 'node_modules/shebang-regex',
  },
  {
    name: 'side-channel',
    version: '1.1.1',
    integrity:
      'sha512-6x6dK6zJdpTzF4sQeNYxwtvBzf6Eg4GtlesS94HOvTudUeyK2WXAaIfmDgsyslYrRBeFIlsi54AYsFGUuhmvrQ==',
    path: 'node_modules/side-channel',
  },
  {
    name: 'side-channel-list',
    version: '1.0.1',
    integrity:
      'sha512-mjn/0bi/oUURjc5Xl7IaWi/OJJJumuoJFQJfDDyO46+hBWsfaVM65TBHq2eoZBhzl9EchxOijpkbRC8SVBQU0w==',
    path: 'node_modules/side-channel-list',
  },
  {
    name: 'side-channel-map',
    version: '1.0.1',
    integrity:
      'sha512-VCjCNfgMsby3tTdo02nbjtM/ewra6jPHmpThenkTYh8pG9ucZ/1P8So4u4FGBek/BjpOVsDCMoLA/iuBKIFXRA==',
    path: 'node_modules/side-channel-map',
  },
  {
    name: 'side-channel-weakmap',
    version: '1.0.2',
    integrity:
      'sha512-WPS/HvHQTYnHisLo9McqBHOJk2FkHO/tlpvldyrnem4aeQp4hai3gythswg6p01oSoTl58rcpiFAjF2br2Ak2A==',
    path: 'node_modules/side-channel-weakmap',
  },
  {
    name: 'signal-exit',
    version: '3.0.7',
    integrity:
      'sha512-wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==',
    path: 'node_modules/signal-exit',
  },
  {
    name: 'statuses',
    version: '2.0.2',
    integrity:
      'sha512-DvEy55V3DB7uknRo+4iOGT5fP1slR8wQohVdknigZPMpMstaKJQWhwiYBACJE3Ul2pTnATihhBYnRhZQHGBiRw==',
    path: 'node_modules/statuses',
  },
  {
    name: 'strnum',
    version: '2.4.0',
    integrity:
      'sha512-sHrVyWWdq28RbhjuJdZsA1SnGRJV6NiXbk6AXBxDOsgAcA+lmpUZCYjOdLBxkXMwis6RRe7dlZt4VlIWFVzkmg==',
    path: 'node_modules/strnum',
  },
  {
    name: 'toidentifier',
    version: '1.0.1',
    integrity:
      'sha512-o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==',
    path: 'node_modules/toidentifier',
  },
  {
    name: 'ts-algebra',
    version: '2.0.0',
    integrity:
      'sha512-FPAhNPFMrkwz76P7cdjdmiShwMynZYN6SgOujD1urY4oNm80Ou9oMdmbR45LotcKOXoy7wSmHkRFE6Mxbrhefw==',
    path: 'node_modules/ts-algebra',
  },
  {
    name: 'tslib',
    version: '2.8.1',
    integrity:
      'sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==',
    path: 'node_modules/tslib',
  },
  {
    name: 'type-is',
    version: '2.1.0',
    integrity:
      'sha512-faYHw0anBbc/kWF3zFTEnxSFOAGUX9GFbOBthvDdLsIlEoWOFOtS0zgCiQYwIskL9iGXZL3kAXD8OoZ4GmMATA==',
    path: 'node_modules/type-is',
  },
  {
    name: 'typebox',
    version: '1.1.38',
    integrity:
      'sha512-pZ0aQPmMmXoUvSbeuWf/Hzsc+avNw/Zd6VeE8CFgkVGWyuHPJvqeJJDeJqLve+K70LvjYIoleGcoJHPT17cWoA==',
    path: 'node_modules/typebox',
  },
  {
    name: 'undici',
    version: '8.5.0',
    integrity:
      'sha512-xamtWoB1EshgjpmlXd7GGm2VfdDtw1+rD8uhry8pSNW3If6S8E0m2T2+orSKeZXEn/aPJMviCpDBA65WJt8zhg==',
    path: 'node_modules/undici',
  },
  {
    name: 'undici-types',
    version: '8.3.0',
    integrity:
      'sha512-j375ScV60dom+YkPFIfTLcOiPxkN/buHz5GobjLhixFuANaNs3C9l4GmrWqejgXWJ7BbJcFYpTEUkS1Ge8bpZQ==',
    path: 'node_modules/undici-types',
  },
  {
    name: 'unpipe',
    version: '1.0.0',
    integrity:
      'sha512-pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==',
    path: 'node_modules/unpipe',
  },
  {
    name: 'vary',
    version: '1.1.2',
    integrity:
      'sha512-BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==',
    path: 'node_modules/vary',
  },
  {
    name: 'web-streams-polyfill',
    version: '3.3.3',
    integrity:
      'sha512-d2JWLCivmZYTSIoge9MsgFCZrt571BikcWGYkjC1khllbTeDlGqZ2D8vD8E/lJa8WGWbb7Plm8/XJYV7IJHZZw==',
    path: 'node_modules/web-streams-polyfill',
  },
  {
    name: 'which',
    version: '2.0.2',
    integrity:
      'sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==',
    path: 'node_modules/which',
  },
  {
    name: 'wrappy',
    version: '1.0.2',
    integrity:
      'sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==',
    path: 'node_modules/wrappy',
  },
  {
    name: 'ws',
    version: '8.21.0',
    integrity:
      'sha512-Vsp28b7DRcimFQvrqu2Wek3z1iYxDCWqHYB8Qsnk/S4RfaCQzPGPyBNuVjJV3cd6UiKtUtp6sNM77gWvzcCH+g==',
    path: 'node_modules/ws',
  },
  {
    name: 'xml-naming',
    version: '0.1.0',
    integrity:
      'sha512-k8KO9hrMyNk6tUWqUfkTEZbezRRpONVOzUTnc97VnCvyj6Tf9lyUR9EDAIeiVLv56jsMcoXEwjW8Kv5yPY52lw==',
    path: 'node_modules/xml-naming',
  },
  {
    name: 'yaml',
    version: '2.9.0',
    integrity:
      'sha512-2AvhNX3mb8zd6Zy7INTtSpl1F15HW6Wnqj0srWlkKLcpYl/gMIMJiyuGq2KeI2YFxUPjdlB+3Lc10seMLtL4cA==',
    path: 'node_modules/yaml',
  },
  {
    name: 'zod',
    version: '4.4.3',
    integrity:
      'sha512-ytENFjIJFl2UwYglde2jchW2Hwm4GJFLDiSXWdTrJQBIN9Fcyp7n4DhxJEiWNAJMV1/BqWfW/kkg71UDcHJyTQ==',
    path: 'node_modules/zod',
  },
  {
    name: 'zod-to-json-schema',
    version: '3.25.2',
    integrity:
      'sha512-O/PgfnpT1xKSDeQYSCfRI5Gy3hPf91mKVDuYLUHZJMiDFptvP41MSnWofm8dnCm0256ZNfZIM7DSzuSMAFnjHA==',
    path: 'node_modules/zod-to-json-schema',
  },
];

export const PI_CLOSURE: NpmClosure = {
  version: '0.80.6',
  entry: 'node_modules/@earendil-works/pi-coding-agent/dist/index.js',
  packages,
};
