#!/usr/bin/env node
/**
 * Regenerate `src/pi-closure.gen.ts` from the repo lockfile + the installed pi package.
 *
 *   pnpm -F @linkcode/assets run generate:pi-closure
 *
 * Run after any `@earendil-works/pi-coding-agent` bump; `closure-gen.test.ts` fails the suite
 * when the committed manifest drifts from pnpm-lock.yaml.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, posix } from 'node:path';
import type { ClosurePackage } from '../src/closure';
import { generateClosure } from '../src/closure-gen';

const PI_PACKAGE = '@earendil-works/pi-coding-agent';
const packageDir = join(import.meta.dirname, '..');
const repoRoot = join(packageDir, '..', '..', '..');

// The manifest bakes the fully resolved entry file: the adapter imports a file URL from the
// asset store, where no package.json `exports` resolution happens. Read the manifest off the
// hoisted node_modules path — pi's exports map does not expose `./package.json` to require().
const piManifest = JSON.parse(
  readFileSync(join(repoRoot, 'node_modules', PI_PACKAGE, 'package.json'), 'utf8'),
) as { main?: string };
if (!piManifest.main) throw new Error(`${PI_PACKAGE} package.json has no "main"`);
const entry = posix.join('node_modules', PI_PACKAGE, piManifest.main);

const closure = generateClosure({
  lockfileText: readFileSync(join(repoRoot, 'pnpm-lock.yaml'), 'utf8'),
  rootPackage: PI_PACKAGE,
  entry,
});

function serializePackage(pkg: ClosurePackage): string {
  const lines = [
    `    name: '${pkg.name}',`,
    `    version: '${pkg.version}',`,
    `    integrity: '${pkg.integrity}',`,
    `    path: '${pkg.path}',`,
  ];
  if (pkg.os) lines.push(`    os: [${pkg.os.map((value) => `'${value}'`).join(', ')}],`);
  if (pkg.cpu) lines.push(`    cpu: [${pkg.cpu.map((value) => `'${value}'`).join(', ')}],`);
  return `  {\n${lines.join('\n')}\n  },`;
}

const generated = `// Generated by scripts/generate-pi-closure.mts from pnpm-lock.yaml — do not edit by hand.
// Regenerate after a ${PI_PACKAGE} bump; closure-gen.test.ts guards against drift.
import type { NpmClosure } from './closure';

const packages: NpmClosure['packages'] = [
${closure.packages.map((pkg) => serializePackage(pkg)).join('\n')}
];

export const PI_CLOSURE: NpmClosure = {
  version: '${closure.version}',
  entry: '${closure.entry}',
  packages,
};
`;

writeFileSync(join(packageDir, 'src', 'pi-closure.gen.ts'), generated);
console.log(`pi closure: ${closure.version}, ${closure.packages.length} packages`);
