import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const RE_MISSING_MODULE = /missing generated config module/;
const RE_SENTINEL = /development sentinel/;
const RE_WRONG_PLATFORM = /targets android, expected ios/;
const RE_PROVENANCE_DRIFT = /disagree on target or provenance/;
const RE_MODULE_SHAPE = /generated config module shape/;

const require = createRequire(import.meta.url);
// The release gate is dependency-free CommonJS because it also runs as the eas-build-pre-install
// hook before node_modules exists; the tests exercise it through its exported functions.
const { loadGeneratedBundle, verifyReleaseConfig } =
  require('../../../../scripts/verify-release-config.cjs') as {
    loadGeneratedBundle: (platform: string, configDir?: string) => { brandId: string };
    verifyReleaseConfig: (platforms: string[], configDir?: string) => void;
  };

function generatedModule(bundle: unknown): string {
  // Mirrors exactly what scripts/render-config-bundle.mts writes.
  return (
    '// Generated by scripts/render-config-bundle.mts — do not edit, do not commit.\n' +
    `const generatedConfigModule: unknown = { bundle: ${JSON.stringify(bundle)} };\n` +
    'export default generatedConfigModule;\n'
  );
}

function bundleFor(platform: string, overrides: Record<string, unknown> = {}): unknown {
  return {
    brandId: 'linkcode',
    channel: 'stable',
    platform,
    provenance: {
      configRevisionId: 'rev-1',
      sourceGitSha: 'a'.repeat(40),
    },
    ...overrides,
  };
}

describe('verify-release-config', () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'verify-release-config-'));
  });
  afterEach(() => {
    rmSync(dir, { force: true, recursive: true });
  });

  const write = (platform: string, bundle: unknown): void => {
    writeFileSync(join(dir, `bundled.generated.${platform}.ts`), generatedModule(bundle));
  };

  it('accepts a matching ios/android pair from one render invocation', () => {
    write('ios', bundleFor('ios'));
    write('android', bundleFor('android'));
    expect(() => verifyReleaseConfig(['android', 'ios'], dir)).not.toThrow();
  });

  it('fails when a generated module is missing', () => {
    write('ios', bundleFor('ios'));
    expect(() => verifyReleaseConfig(['android', 'ios'], dir)).toThrow(RE_MISSING_MODULE);
  });

  it('rejects the development sentinel in a generated module', () => {
    write('ios', null);
    expect(() => loadGeneratedBundle('ios', dir)).toThrow(RE_SENTINEL);
  });

  it('rejects a module rendered for the wrong platform', () => {
    write('ios', bundleFor('android'));
    expect(() => loadGeneratedBundle('ios', dir)).toThrow(RE_WRONG_PLATFORM);
  });

  it('rejects platform modules with drifted provenance', () => {
    write('ios', bundleFor('ios'));
    write(
      'android',
      bundleFor('android', {
        provenance: { configRevisionId: 'rev-1', sourceGitSha: 'b'.repeat(40) },
      }),
    );
    expect(() => verifyReleaseConfig(['android', 'ios'], dir)).toThrow(RE_PROVENANCE_DRIFT);
  });

  it('rejects platform modules with drifted targets', () => {
    write('ios', bundleFor('ios'));
    write('android', bundleFor('android', { channel: 'canary' }));
    expect(() => verifyReleaseConfig(['android', 'ios'], dir)).toThrow(RE_PROVENANCE_DRIFT);
  });

  it('rejects a file that lost the generated module shape', () => {
    writeFileSync(join(dir, 'bundled.generated.ios.ts'), 'export default {};\n');
    expect(() => loadGeneratedBundle('ios', dir)).toThrow(RE_MODULE_SHAPE);
  });
});
