export const DESKTOP_IPC_SPAN_NAMES = [
  'ipc app.check-for-updates',
  'ipc app.on-open-settings',
  'ipc app.on-updater-status',
  'ipc app.version',
  'ipc cloud.auth.get-user',
  'ipc cloud.auth.request',
  'ipc cloud.auth.sign-out',
  'ipc cloud.claim-deep-link',
  'ipc cloud.im.bindings',
  'ipc cloud.im.create-binding',
  'ipc cloud.im.delete-binding',
  'ipc cloud.im.link-telegram',
  'ipc cloud.im.overview',
  'ipc cloud.im.preferences',
  'ipc cloud.im.set-preferences',
  'ipc cloud.im.unlink-telegram',
  'ipc cloud.im.update-binding',
  'ipc cloud.list-hosts',
  'ipc daemon.is-managed',
  'ipc daemon.on-runtime-changed',
  'ipc daemon.resolve-url',
  'ipc daemon.retry',
  'ipc fs.pick-file',
  'ipc notifications.notify',
  'ipc notifications.on-click',
  'ipc settings.get',
  'ipc settings.set',
  'ipc settings.snapshot',
  'ipc window.close',
  'ipc window.is-maximized',
  'ipc window.minimize',
  'ipc window.on-maximized-change',
  'ipc window.toggle-maximize',
] as const;

export const DESKTOP_TRANSACTION_NAMES = [
  'desktop main startup',
  'desktop renderer bootstrap',
  'desktop thread',
  'desktop new-thread',
  'desktop settings',
  'desktop automations',
  'desktop main operation',
  'desktop renderer operation',
  ...DESKTOP_IPC_SPAN_NAMES,
] as const;

export const DESKTOP_SPAN_NAMES = ['<DesktopApp>', ...DESKTOP_IPC_SPAN_NAMES] as const;
