// Renders the iOS and Android build bundles through the pinned config publisher checkout into
// bundled.generated.<platform>.ts, which Metro resolves over the committed { bundle: null }
// sentinel. Run via `pnpm -F @linkcode/mobile config:render --publisher …` (no `--` separator).
// Every input is an explicit pin; there is no default checkout, no fetch, and no stale fallback.
import { copyFile, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { renderConfigBundleWithPublisher } from '@linkcode/common/node';

const USAGE = String.raw`Usage: config:render \
  --publisher <dir>             config publisher checkout root \
  --publisher-git-sha <sha>     exact lowercase 40-hex commit the publisher checkout must be at \
  --structural <dir>            structural config source directory (contains brands.manifest.yaml) \
  --source-git-sha <sha>        exact lowercase 40-hex commit the source checkout must be at \
  --revision <file>             config revision metadata JSON \
  --keyrings <file>             public keyrings JSON \
  --brand <id> --channel <canary|stable> \
  --telemetry-endpoint <url>    authenticated telemetry endpoint for this target \
  --release-manifest-ios <file>     optional per-target manifest digest-binding inputs/snapshot \
  --release-manifest-android <file> required together with --release-manifest-ios`;

const MOBILE_PLATFORMS = ['ios', 'android'] as const;

function bail(message: string): never {
  console.error(`config:render: ${message}\n\n${USAGE}`);
  process.exit(1);
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      brand: { type: 'string' },
      channel: { type: 'string' },
      keyrings: { type: 'string' },
      publisher: { type: 'string' },
      'publisher-git-sha': { type: 'string' },
      'release-manifest-android': { type: 'string' },
      'release-manifest-ios': { type: 'string' },
      revision: { type: 'string' },
      'source-git-sha': { type: 'string' },
      structural: { type: 'string' },
      'telemetry-endpoint': { type: 'string' },
    },
    strict: true,
  });

  const channel = values.channel ?? bail('--channel is required');
  if (channel !== 'canary' && channel !== 'stable') {
    bail('--channel must be canary or stable');
  }
  const releaseManifests = {
    android: values['release-manifest-android'],
    ios: values['release-manifest-ios'],
  };
  if ((releaseManifests.ios === undefined) !== (releaseManifests.android === undefined)) {
    bail('--release-manifest-ios and --release-manifest-android must be passed together');
  }
  const configDir = resolve(import.meta.dirname, '../src/runtime/config');
  const workDir = await mkdtemp(join(tmpdir(), 'linkcode-config-render-'));

  try {
    // Both platforms render in one invocation so they can never drift apart in source or inputs.
    for (const platform of MOBILE_PLATFORMS) {
      const outPath = join(workDir, `${platform}.json`);
      // eslint-disable-next-line no-await-in-loop -- renders share pinned checkouts sequentially
      const bundle = await renderConfigBundleWithPublisher({
        brandId: values.brand ?? bail('--brand is required'),
        channel,
        keyringsPath: values.keyrings ?? bail('--keyrings is required'),
        outPath,
        platform,
        publisherDir: values.publisher ?? bail('--publisher is required'),
        publisherGitSha: values['publisher-git-sha'] ?? bail('--publisher-git-sha is required'),
        releaseManifestPath: releaseManifests[platform],
        revisionPath: values.revision ?? bail('--revision is required'),
        sourceGitSha: values['source-git-sha'] ?? bail('--source-git-sha is required'),
        structuralDir: values.structural ?? bail('--structural is required'),
        telemetryEndpoint: values['telemetry-endpoint'] ?? bail('--telemetry-endpoint is required'),
      });
      // eslint-disable-next-line no-await-in-loop -- read back the file the render just wrote
      const rendered = await readFile(outPath, 'utf8');
      // The generated module shape is load-bearing: smoke-native-entry-export.cjs parses the
      // object literal back out of it to verify the compiled Hermes export.
      // eslint-disable-next-line no-await-in-loop -- one small write per platform
      await writeFile(
        join(workDir, `bundled.generated.${platform}.ts`),
        '// Generated by scripts/render-config-bundle.mts — do not edit, do not commit.\n' +
          `const generatedConfigModule: unknown = { bundle: ${rendered.trim()} };\n` +
          'export default generatedConfigModule;\n',
      );
      console.log(
        `Rendered ${bundle.brandId}/${platform}/${bundle.channel} from source ` +
          `${bundle.provenance.sourceGitSha} (revision ${bundle.provenance.configRevisionId})`,
      );
    }
    await Promise.all(
      MOBILE_PLATFORMS.map((platform) =>
        copyFile(
          join(workDir, `bundled.generated.${platform}.ts`),
          join(configDir, `bundled.generated.${platform}.ts`),
        ),
      ),
    );
  } finally {
    await rm(workDir, { force: true, recursive: true });
  }
}

void main();
